version: "3"
services:
    api:
        build:
            args:
                NODE_ENV: development
        volumes:
            - ./src:/app/src
            - /app/node_modules
            - /app/dist
        ports:
            - 8080:8080
    postgres:
        ports:
            - 5431:5432